version: '3.9'

services:
  db:
    image: postgres:15
    container_name: mottu_postgres
    restart: always
    environment:
      POSTGRES_USER: mottu
      POSTGRES_PASSWORD: mottu123
      POSTGRES_DB: mottu_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mottu_api
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=mottu_db;Username=mottu;Password=mottu123
    ports:
      - "5000:8080"

volumes:
  pgdata: